all:
	pdflatex slides.tex
	bibtex slides.aux
	pdflatex slides.tex
	pdflatex slides.tex

single:
	pdflatex slides.tex

clean:
	rm slides.aux
	rm slides.bbl
	rm slides.blg
	rm slides.log
	rm slides.nav
	rm slides.out
	rm slides.snm
	rm slides.toc
