all:
	pdflatex report.tex
	bibtex report.aux
	pdflatex report.tex
	pdflatex report.tex

single:
	pdflatex report.tex

clean:
	rm report.aux
	rm report.bbl
	rm report.blg
	rm report.log
	rm report.out
	rm report.snm
	rm report.toc
